package com.keji.green.lit.engine.mapper;

import com.keji.green.lit.engine.model.TradePaymentOrder;
import com.keji.green.lit.engine.model.TradePaymentRecord;

import java.util.Map;

public interface TradePaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_record
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_record
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    int insert(TradePaymentRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_record
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    int insertSelective(TradePaymentRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_record
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    TradePaymentRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_record
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    int updateByPrimaryKeySelective(TradePaymentRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_record
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    int updateByPrimaryKey(TradePaymentRecord row);

    TradePaymentRecord queryTradePaymentRecord(Map<String, Object> params);

}