package com.keji.green.lit.engine.mapper;

import com.keji.green.lit.engine.model.TradePaymentOrder;
import org.apache.ibatis.annotations.Mapper;

import java.util.Map;

@Mapper
public interface TradePaymentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_order
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_order
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    int insert(TradePaymentOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_order
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    int insertSelective(TradePaymentOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_order
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    TradePaymentOrder selectByPrimaryKey(Long id);

    TradePaymentOrder queryTradePaymentOrder(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_order
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    int updateByPrimaryKeySelective(TradePaymentOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_payment_order
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    int updateByPrimaryKey(TradePaymentOrder row);
}