package com.keji.green.lit.engine.model;

import java.math.BigDecimal;
import java.util.Date;

public class TradePaymentOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.id
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.sharding_key
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private int shardingKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.user_id
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.version
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.create_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.editor
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.creater
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.edit_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.status
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.product_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.merchant_order_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String merchantOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_amount
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_from
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String orderFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.merchant_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.merchant_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_date
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_ip
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String orderIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_referer_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String orderRefererUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.return_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String returnUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.notify_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.cancel_reason
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String cancelReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.order_period
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Integer orderPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.expire_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.pay_way_code
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String payWayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.pay_way_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String payWayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.remark
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.trx_type
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String trxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.trx_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String trxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.pay_type_code
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String payTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.pay_type_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String payTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.fund_into_type
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String fundIntoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.is_refund
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String isRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.refund_times
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private Integer refundTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.success_refund_amount
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private BigDecimal successRefundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.field1
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.field2
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.field3
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.field4
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String field4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_order.field5
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    private String field5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.id
     *
     * @return the value of trade_payment_order.id
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.id
     *
     * @param id the value for trade_payment_order.id
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.sharding_key
     *
     * @return the value of trade_payment_order.sharding_key
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public int getShardingKey() {
        return shardingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.sharding_key
     *
     * @param shardingKey the value for trade_payment_order.sharding_key
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setShardingKey(int shardingKey) {
        this.shardingKey = shardingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.user_id
     *
     * @return the value of trade_payment_order.user_id
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.user_id
     *
     * @param userId the value for trade_payment_order.user_id
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.version
     *
     * @return the value of trade_payment_order.version
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.version
     *
     * @param version the value for trade_payment_order.version
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.create_time
     *
     * @return the value of trade_payment_order.create_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.create_time
     *
     * @param createTime the value for trade_payment_order.create_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.editor
     *
     * @return the value of trade_payment_order.editor
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.editor
     *
     * @param editor the value for trade_payment_order.editor
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.creater
     *
     * @return the value of trade_payment_order.creater
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.creater
     *
     * @param creater the value for trade_payment_order.creater
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.edit_time
     *
     * @return the value of trade_payment_order.edit_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.edit_time
     *
     * @param editTime the value for trade_payment_order.edit_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.status
     *
     * @return the value of trade_payment_order.status
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.status
     *
     * @param status the value for trade_payment_order.status
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.product_name
     *
     * @return the value of trade_payment_order.product_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.product_name
     *
     * @param productName the value for trade_payment_order.product_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.merchant_order_no
     *
     * @return the value of trade_payment_order.merchant_order_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.merchant_order_no
     *
     * @param merchantOrderNo the value for trade_payment_order.merchant_order_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_amount
     *
     * @return the value of trade_payment_order.order_amount
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_amount
     *
     * @param orderAmount the value for trade_payment_order.order_amount
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_from
     *
     * @return the value of trade_payment_order.order_from
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_from
     *
     * @param orderFrom the value for trade_payment_order.order_from
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderFrom(String orderFrom) {
        this.orderFrom = orderFrom == null ? null : orderFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.merchant_name
     *
     * @return the value of trade_payment_order.merchant_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.merchant_name
     *
     * @param merchantName the value for trade_payment_order.merchant_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.merchant_no
     *
     * @return the value of trade_payment_order.merchant_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.merchant_no
     *
     * @param merchantNo the value for trade_payment_order.merchant_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_time
     *
     * @return the value of trade_payment_order.order_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_time
     *
     * @param orderTime the value for trade_payment_order.order_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_date
     *
     * @return the value of trade_payment_order.order_date
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_date
     *
     * @param orderDate the value for trade_payment_order.order_date
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_ip
     *
     * @return the value of trade_payment_order.order_ip
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getOrderIp() {
        return orderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_ip
     *
     * @param orderIp the value for trade_payment_order.order_ip
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderIp(String orderIp) {
        this.orderIp = orderIp == null ? null : orderIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_referer_url
     *
     * @return the value of trade_payment_order.order_referer_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getOrderRefererUrl() {
        return orderRefererUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_referer_url
     *
     * @param orderRefererUrl the value for trade_payment_order.order_referer_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderRefererUrl(String orderRefererUrl) {
        this.orderRefererUrl = orderRefererUrl == null ? null : orderRefererUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.return_url
     *
     * @return the value of trade_payment_order.return_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.return_url
     *
     * @param returnUrl the value for trade_payment_order.return_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl == null ? null : returnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.notify_url
     *
     * @return the value of trade_payment_order.notify_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.notify_url
     *
     * @param notifyUrl the value for trade_payment_order.notify_url
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.cancel_reason
     *
     * @return the value of trade_payment_order.cancel_reason
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.cancel_reason
     *
     * @param cancelReason the value for trade_payment_order.cancel_reason
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.order_period
     *
     * @return the value of trade_payment_order.order_period
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Integer getOrderPeriod() {
        return orderPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.order_period
     *
     * @param orderPeriod the value for trade_payment_order.order_period
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setOrderPeriod(Integer orderPeriod) {
        this.orderPeriod = orderPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.expire_time
     *
     * @return the value of trade_payment_order.expire_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.expire_time
     *
     * @param expireTime the value for trade_payment_order.expire_time
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.pay_way_code
     *
     * @return the value of trade_payment_order.pay_way_code
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getPayWayCode() {
        return payWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.pay_way_code
     *
     * @param payWayCode the value for trade_payment_order.pay_way_code
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setPayWayCode(String payWayCode) {
        this.payWayCode = payWayCode == null ? null : payWayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.pay_way_name
     *
     * @return the value of trade_payment_order.pay_way_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.pay_way_name
     *
     * @param payWayName the value for trade_payment_order.pay_way_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.remark
     *
     * @return the value of trade_payment_order.remark
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.remark
     *
     * @param remark the value for trade_payment_order.remark
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.trx_type
     *
     * @return the value of trade_payment_order.trx_type
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getTrxType() {
        return trxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.trx_type
     *
     * @param trxType the value for trade_payment_order.trx_type
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setTrxType(String trxType) {
        this.trxType = trxType == null ? null : trxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.trx_no
     *
     * @return the value of trade_payment_order.trx_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getTrxNo() {
        return trxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.trx_no
     *
     * @param trxNo the value for trade_payment_order.trx_no
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setTrxNo(String trxNo) {
        this.trxNo = trxNo == null ? null : trxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.pay_type_code
     *
     * @return the value of trade_payment_order.pay_type_code
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getPayTypeCode() {
        return payTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.pay_type_code
     *
     * @param payTypeCode the value for trade_payment_order.pay_type_code
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setPayTypeCode(String payTypeCode) {
        this.payTypeCode = payTypeCode == null ? null : payTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.pay_type_name
     *
     * @return the value of trade_payment_order.pay_type_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getPayTypeName() {
        return payTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.pay_type_name
     *
     * @param payTypeName the value for trade_payment_order.pay_type_name
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName == null ? null : payTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.fund_into_type
     *
     * @return the value of trade_payment_order.fund_into_type
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getFundIntoType() {
        return fundIntoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.fund_into_type
     *
     * @param fundIntoType the value for trade_payment_order.fund_into_type
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setFundIntoType(String fundIntoType) {
        this.fundIntoType = fundIntoType == null ? null : fundIntoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.is_refund
     *
     * @return the value of trade_payment_order.is_refund
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.is_refund
     *
     * @param isRefund the value for trade_payment_order.is_refund
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setIsRefund(String isRefund) {
        this.isRefund = isRefund == null ? null : isRefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.refund_times
     *
     * @return the value of trade_payment_order.refund_times
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public Integer getRefundTimes() {
        return refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.refund_times
     *
     * @param refundTimes the value for trade_payment_order.refund_times
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setRefundTimes(Integer refundTimes) {
        this.refundTimes = refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.success_refund_amount
     *
     * @return the value of trade_payment_order.success_refund_amount
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public BigDecimal getSuccessRefundAmount() {
        return successRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.success_refund_amount
     *
     * @param successRefundAmount the value for trade_payment_order.success_refund_amount
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setSuccessRefundAmount(BigDecimal successRefundAmount) {
        this.successRefundAmount = successRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.field1
     *
     * @return the value of trade_payment_order.field1
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.field1
     *
     * @param field1 the value for trade_payment_order.field1
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.field2
     *
     * @return the value of trade_payment_order.field2
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.field2
     *
     * @param field2 the value for trade_payment_order.field2
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.field3
     *
     * @return the value of trade_payment_order.field3
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.field3
     *
     * @param field3 the value for trade_payment_order.field3
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.field4
     *
     * @return the value of trade_payment_order.field4
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.field4
     *
     * @param field4 the value for trade_payment_order.field4
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_order.field5
     *
     * @return the value of trade_payment_order.field5
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_order.field5
     *
     * @param field5 the value for trade_payment_order.field5
     *
     * @mbg.generated Sat May 17 18:37:25 CST 2025
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }
}