package com.keji.green.lit.engine.model;

import java.math.BigDecimal;
import java.util.Date;

public class TradePaymentRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.id
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.sharding_key
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private short shardingKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.user_id
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.version
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.create_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.status
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.editor
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.creater
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.edit_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.product_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.merchant_order_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String merchantOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.trx_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String trxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.bank_order_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String bankOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.bank_trx_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String bankTrxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.merchant_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.merchant_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.payer_user_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payerUserNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.payer_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.payer_pay_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal payerPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.payer_fee
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal payerFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.payer_account_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payerAccountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.receiver_user_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String receiverUserNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.receiver_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.receiver_pay_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal receiverPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.receiver_fee
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal receiverFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.receiver_account_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String receiverAccountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.order_ip
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String orderIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.order_referer_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String orderRefererUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.order_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.plat_income
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal platIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.fee_rate
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal feeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.plat_cost
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal platCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.plat_profit
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal platProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.return_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String returnUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.notify_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.pay_way_code
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payWayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.pay_way_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payWayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.pay_success_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Date paySuccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.complete_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Date completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.is_refund
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String isRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.refund_times
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private Integer refundTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.success_refund_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private BigDecimal successRefundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.trx_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String trxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.order_from
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String orderFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.pay_type_code
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.pay_type_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String payTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.fund_into_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String fundIntoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.remark
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.field1
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.field2
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.field3
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.field4
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String field4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.field5
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String field5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_payment_record.bank_return_msg
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    private String bankReturnMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.id
     *
     * @return the value of trade_payment_record.id
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.id
     *
     * @param id the value for trade_payment_record.id
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.sharding_key
     *
     * @return the value of trade_payment_record.sharding_key
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public short getShardingKey() {
        return shardingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.sharding_key
     *
     * @param shardingKey the value for trade_payment_record.sharding_key
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setShardingKey(short shardingKey) {
        this.shardingKey = shardingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.user_id
     *
     * @return the value of trade_payment_record.user_id
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.user_id
     *
     * @param userId the value for trade_payment_record.user_id
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.version
     *
     * @return the value of trade_payment_record.version
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.version
     *
     * @param version the value for trade_payment_record.version
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.create_time
     *
     * @return the value of trade_payment_record.create_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.create_time
     *
     * @param createTime the value for trade_payment_record.create_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.status
     *
     * @return the value of trade_payment_record.status
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.status
     *
     * @param status the value for trade_payment_record.status
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.editor
     *
     * @return the value of trade_payment_record.editor
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.editor
     *
     * @param editor the value for trade_payment_record.editor
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.creater
     *
     * @return the value of trade_payment_record.creater
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.creater
     *
     * @param creater the value for trade_payment_record.creater
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.edit_time
     *
     * @return the value of trade_payment_record.edit_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.edit_time
     *
     * @param editTime the value for trade_payment_record.edit_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.product_name
     *
     * @return the value of trade_payment_record.product_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.product_name
     *
     * @param productName the value for trade_payment_record.product_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.merchant_order_no
     *
     * @return the value of trade_payment_record.merchant_order_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.merchant_order_no
     *
     * @param merchantOrderNo the value for trade_payment_record.merchant_order_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.trx_no
     *
     * @return the value of trade_payment_record.trx_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getTrxNo() {
        return trxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.trx_no
     *
     * @param trxNo the value for trade_payment_record.trx_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setTrxNo(String trxNo) {
        this.trxNo = trxNo == null ? null : trxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.bank_order_no
     *
     * @return the value of trade_payment_record.bank_order_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getBankOrderNo() {
        return bankOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.bank_order_no
     *
     * @param bankOrderNo the value for trade_payment_record.bank_order_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setBankOrderNo(String bankOrderNo) {
        this.bankOrderNo = bankOrderNo == null ? null : bankOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.bank_trx_no
     *
     * @return the value of trade_payment_record.bank_trx_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getBankTrxNo() {
        return bankTrxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.bank_trx_no
     *
     * @param bankTrxNo the value for trade_payment_record.bank_trx_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setBankTrxNo(String bankTrxNo) {
        this.bankTrxNo = bankTrxNo == null ? null : bankTrxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.merchant_name
     *
     * @return the value of trade_payment_record.merchant_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.merchant_name
     *
     * @param merchantName the value for trade_payment_record.merchant_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.merchant_no
     *
     * @return the value of trade_payment_record.merchant_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.merchant_no
     *
     * @param merchantNo the value for trade_payment_record.merchant_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.payer_user_no
     *
     * @return the value of trade_payment_record.payer_user_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayerUserNo() {
        return payerUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.payer_user_no
     *
     * @param payerUserNo the value for trade_payment_record.payer_user_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayerUserNo(String payerUserNo) {
        this.payerUserNo = payerUserNo == null ? null : payerUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.payer_name
     *
     * @return the value of trade_payment_record.payer_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.payer_name
     *
     * @param payerName the value for trade_payment_record.payer_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.payer_pay_amount
     *
     * @return the value of trade_payment_record.payer_pay_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getPayerPayAmount() {
        return payerPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.payer_pay_amount
     *
     * @param payerPayAmount the value for trade_payment_record.payer_pay_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayerPayAmount(BigDecimal payerPayAmount) {
        this.payerPayAmount = payerPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.payer_fee
     *
     * @return the value of trade_payment_record.payer_fee
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getPayerFee() {
        return payerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.payer_fee
     *
     * @param payerFee the value for trade_payment_record.payer_fee
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayerFee(BigDecimal payerFee) {
        this.payerFee = payerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.payer_account_type
     *
     * @return the value of trade_payment_record.payer_account_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayerAccountType() {
        return payerAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.payer_account_type
     *
     * @param payerAccountType the value for trade_payment_record.payer_account_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayerAccountType(String payerAccountType) {
        this.payerAccountType = payerAccountType == null ? null : payerAccountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.receiver_user_no
     *
     * @return the value of trade_payment_record.receiver_user_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getReceiverUserNo() {
        return receiverUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.receiver_user_no
     *
     * @param receiverUserNo the value for trade_payment_record.receiver_user_no
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setReceiverUserNo(String receiverUserNo) {
        this.receiverUserNo = receiverUserNo == null ? null : receiverUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.receiver_name
     *
     * @return the value of trade_payment_record.receiver_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.receiver_name
     *
     * @param receiverName the value for trade_payment_record.receiver_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.receiver_pay_amount
     *
     * @return the value of trade_payment_record.receiver_pay_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getReceiverPayAmount() {
        return receiverPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.receiver_pay_amount
     *
     * @param receiverPayAmount the value for trade_payment_record.receiver_pay_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setReceiverPayAmount(BigDecimal receiverPayAmount) {
        this.receiverPayAmount = receiverPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.receiver_fee
     *
     * @return the value of trade_payment_record.receiver_fee
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getReceiverFee() {
        return receiverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.receiver_fee
     *
     * @param receiverFee the value for trade_payment_record.receiver_fee
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setReceiverFee(BigDecimal receiverFee) {
        this.receiverFee = receiverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.receiver_account_type
     *
     * @return the value of trade_payment_record.receiver_account_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getReceiverAccountType() {
        return receiverAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.receiver_account_type
     *
     * @param receiverAccountType the value for trade_payment_record.receiver_account_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setReceiverAccountType(String receiverAccountType) {
        this.receiverAccountType = receiverAccountType == null ? null : receiverAccountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.order_ip
     *
     * @return the value of trade_payment_record.order_ip
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getOrderIp() {
        return orderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.order_ip
     *
     * @param orderIp the value for trade_payment_record.order_ip
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setOrderIp(String orderIp) {
        this.orderIp = orderIp == null ? null : orderIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.order_referer_url
     *
     * @return the value of trade_payment_record.order_referer_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getOrderRefererUrl() {
        return orderRefererUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.order_referer_url
     *
     * @param orderRefererUrl the value for trade_payment_record.order_referer_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setOrderRefererUrl(String orderRefererUrl) {
        this.orderRefererUrl = orderRefererUrl == null ? null : orderRefererUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.order_amount
     *
     * @return the value of trade_payment_record.order_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.order_amount
     *
     * @param orderAmount the value for trade_payment_record.order_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.plat_income
     *
     * @return the value of trade_payment_record.plat_income
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getPlatIncome() {
        return platIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.plat_income
     *
     * @param platIncome the value for trade_payment_record.plat_income
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPlatIncome(BigDecimal platIncome) {
        this.platIncome = platIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.fee_rate
     *
     * @return the value of trade_payment_record.fee_rate
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.fee_rate
     *
     * @param feeRate the value for trade_payment_record.fee_rate
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.plat_cost
     *
     * @return the value of trade_payment_record.plat_cost
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getPlatCost() {
        return platCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.plat_cost
     *
     * @param platCost the value for trade_payment_record.plat_cost
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPlatCost(BigDecimal platCost) {
        this.platCost = platCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.plat_profit
     *
     * @return the value of trade_payment_record.plat_profit
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getPlatProfit() {
        return platProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.plat_profit
     *
     * @param platProfit the value for trade_payment_record.plat_profit
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPlatProfit(BigDecimal platProfit) {
        this.platProfit = platProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.return_url
     *
     * @return the value of trade_payment_record.return_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.return_url
     *
     * @param returnUrl the value for trade_payment_record.return_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl == null ? null : returnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.notify_url
     *
     * @return the value of trade_payment_record.notify_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.notify_url
     *
     * @param notifyUrl the value for trade_payment_record.notify_url
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.pay_way_code
     *
     * @return the value of trade_payment_record.pay_way_code
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayWayCode() {
        return payWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.pay_way_code
     *
     * @param payWayCode the value for trade_payment_record.pay_way_code
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayWayCode(String payWayCode) {
        this.payWayCode = payWayCode == null ? null : payWayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.pay_way_name
     *
     * @return the value of trade_payment_record.pay_way_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.pay_way_name
     *
     * @param payWayName the value for trade_payment_record.pay_way_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.pay_success_time
     *
     * @return the value of trade_payment_record.pay_success_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Date getPaySuccessTime() {
        return paySuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.pay_success_time
     *
     * @param paySuccessTime the value for trade_payment_record.pay_success_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPaySuccessTime(Date paySuccessTime) {
        this.paySuccessTime = paySuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.complete_time
     *
     * @return the value of trade_payment_record.complete_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.complete_time
     *
     * @param completeTime the value for trade_payment_record.complete_time
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.is_refund
     *
     * @return the value of trade_payment_record.is_refund
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.is_refund
     *
     * @param isRefund the value for trade_payment_record.is_refund
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setIsRefund(String isRefund) {
        this.isRefund = isRefund == null ? null : isRefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.refund_times
     *
     * @return the value of trade_payment_record.refund_times
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public Integer getRefundTimes() {
        return refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.refund_times
     *
     * @param refundTimes the value for trade_payment_record.refund_times
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setRefundTimes(Integer refundTimes) {
        this.refundTimes = refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.success_refund_amount
     *
     * @return the value of trade_payment_record.success_refund_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public BigDecimal getSuccessRefundAmount() {
        return successRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.success_refund_amount
     *
     * @param successRefundAmount the value for trade_payment_record.success_refund_amount
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setSuccessRefundAmount(BigDecimal successRefundAmount) {
        this.successRefundAmount = successRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.trx_type
     *
     * @return the value of trade_payment_record.trx_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getTrxType() {
        return trxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.trx_type
     *
     * @param trxType the value for trade_payment_record.trx_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setTrxType(String trxType) {
        this.trxType = trxType == null ? null : trxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.order_from
     *
     * @return the value of trade_payment_record.order_from
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.order_from
     *
     * @param orderFrom the value for trade_payment_record.order_from
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setOrderFrom(String orderFrom) {
        this.orderFrom = orderFrom == null ? null : orderFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.pay_type_code
     *
     * @return the value of trade_payment_record.pay_type_code
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayTypeCode() {
        return payTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.pay_type_code
     *
     * @param payTypeCode the value for trade_payment_record.pay_type_code
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayTypeCode(String payTypeCode) {
        this.payTypeCode = payTypeCode == null ? null : payTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.pay_type_name
     *
     * @return the value of trade_payment_record.pay_type_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getPayTypeName() {
        return payTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.pay_type_name
     *
     * @param payTypeName the value for trade_payment_record.pay_type_name
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName == null ? null : payTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.fund_into_type
     *
     * @return the value of trade_payment_record.fund_into_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getFundIntoType() {
        return fundIntoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.fund_into_type
     *
     * @param fundIntoType the value for trade_payment_record.fund_into_type
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setFundIntoType(String fundIntoType) {
        this.fundIntoType = fundIntoType == null ? null : fundIntoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.remark
     *
     * @return the value of trade_payment_record.remark
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.remark
     *
     * @param remark the value for trade_payment_record.remark
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.field1
     *
     * @return the value of trade_payment_record.field1
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.field1
     *
     * @param field1 the value for trade_payment_record.field1
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.field2
     *
     * @return the value of trade_payment_record.field2
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.field2
     *
     * @param field2 the value for trade_payment_record.field2
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.field3
     *
     * @return the value of trade_payment_record.field3
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.field3
     *
     * @param field3 the value for trade_payment_record.field3
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.field4
     *
     * @return the value of trade_payment_record.field4
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.field4
     *
     * @param field4 the value for trade_payment_record.field4
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.field5
     *
     * @return the value of trade_payment_record.field5
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.field5
     *
     * @param field5 the value for trade_payment_record.field5
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_payment_record.bank_return_msg
     *
     * @return the value of trade_payment_record.bank_return_msg
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public String getBankReturnMsg() {
        return bankReturnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_payment_record.bank_return_msg
     *
     * @param bankReturnMsg the value for trade_payment_record.bank_return_msg
     *
     * @mbg.generated Sat May 17 18:33:28 CST 2025
     */
    public void setBankReturnMsg(String bankReturnMsg) {
        this.bankReturnMsg = bankReturnMsg == null ? null : bankReturnMsg.trim();
    }
}